{{- if .Values.browserService.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "selenosis-deploy.componentName" (dict "root" . "component" "browser-service") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "selenosis-deploy.labels" . | nindent 4 }}
    app.kubernetes.io/component: browser-service
spec:
  replicas: {{ .Values.browserService.replicas }}
  selector:
    matchLabels:
      {{- include "selenosis-deploy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: browser-service
  template:
    metadata:
      labels:
        {{- include "selenosis-deploy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: browser-service
    spec:
      serviceAccountName: {{ default (include "selenosis-deploy.componentName" (dict "root" . "component" "browser-service")) .Values.browserService.serviceAccount.name }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}

      {{- with (.Values.browserService.nodeSelector | default .Values.common.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with (.Values.browserService.tolerations | default .Values.common.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with (.Values.browserService.affinity | default .Values.common.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: browser-service
        image: {{ .Values.browserService.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        args:
          - "--listen={{ .Values.browserService.listenAddr }}"
        ports:
          - name: http
            containerPort: {{ .Values.browserService.service.port }}
        resources:
          {{- toYaml .Values.browserService.resources | nindent 10 }}
{{- end -}}
